/* Local design fixtures only. No API connector, live backend, file upload, or agent invocation. */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const params=new URLSearchParams(location.search),page=document.body.dataset.page;
const rosterKey=params.get('roster')==='alternate'?'alternate':'primary';
const roster=fixtures[rosterKey];
const requestedAgent=params.get('agent'),agent=roster.find(a=>a.agentId===requestedAgent)||(!requestedAgent?roster[0]:null);
const sessionId=params.get('session')||'research-plan';
let sessions=structuredClone(fixtures.sessions),activeSession=sessions.find(s=>s.sessionId===sessionId);
let state=params.get('state')||'populated';
if(page==='conversation'&&params.has('session')&&!activeSession)state='missing';
let docs=['Workspace overview.md','Response preferences.md'];
let instructions='Be clear and practical. Explain the reasoning, then suggest a useful next step.';
const lastQuestion='Can you turn that into a short checklist?';
let previewSubmitted='',submittedFromEmpty=false,feedbackTimer;
function ico(n){return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(icons[n]||icons.chat)+'</svg>'}
function esc(x){const d=document.createElement('div');d.textContent=String(x);return d.innerHTML.replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function notify(t){$('#feedback').textContent=t;clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>$('#feedback').textContent='',7000)}
function url(name,extra={}){const q=new URLSearchParams();if(rosterKey!=='primary')q.set('roster',rosterKey);if(document.documentElement.dataset.review==='false')q.set('review','0');for(const [k,v]of Object.entries(extra))if(v!==undefined&&v!==null)q.set(k,v);return name+(q.size?'?'+q.toString():'')}
function workspaceURL(){return url('workspace.html',{agent:agent?.agentId})}
function chatURL(s='research-plan',st){return url('conversation.html',{agent:agent?.agentId,session:s,state:st})}
function newURL(){return url('conversation.html',{agent:agent?.agentId,state:'empty'})}
function updateTheme(){const dark=document.documentElement.classList.contains('dark');$$('[data-theme-toggle]').forEach(b=>{b.innerHTML=ico(dark?'sun':'moon')+'<span>'+(dark?'Light mode':'Dark mode')+'</span>';b.setAttribute('aria-label','Switch to '+(dark?'light':'dark')+' mode')});$$('[data-swatch]').forEach(e=>e.textContent='#'+palettes[dark?'dark':'light'][e.dataset.swatch].toUpperCase())}
$$('[data-theme-toggle]').forEach(b=>b.onclick=()=>{document.documentElement.classList.toggle('dark');try{localStorage.setItem('stark-design-theme',document.documentElement.classList.contains('dark')?'dark':'light')}catch{}updateTheme()});updateTheme();
function syncLinks(){$$('[data-route=directory]').forEach(a=>a.href=url('agents-directory.html'));$$('[data-route=workspace]').forEach(a=>a.href=workspaceURL());$$('a[data-new]').forEach(a=>{a.href=page==='directory'?'#agent-filter':agent?newURL():url('agents-directory.html');if(page==='directory'){a.innerHTML=ico('plus')+'Choose an agent';a.onclick=()=>{$('#nav-dialog').open&&$('#nav-dialog').close();requestAnimationFrame(()=>$('#agent-filter').focus())}}});}
function renderNav(){$$('[data-agent-list]').forEach(el=>el.innerHTML=(page==='directory'&&['empty','unavailable','loading'].includes(state)?[]:roster).map(a=>'<a class="nav-item" href="'+url('workspace.html',{agent:a.agentId})+'" '+(a.agentId===agent?.agentId&&page!=='directory'?'aria-current="page"':'')+'>'+ico(a.icon)+'<span>'+esc(a.displayName)+'</span></a>').join(''));if(page==='directory')$$('nav [data-route=directory]').forEach(e=>e.setAttribute('aria-current','page'));$$('.session-nav').forEach(e=>e.hidden=page!=='conversation');$$('[data-session-list]').forEach(e=>e.innerHTML=sessions.map(s=>'<a class="nav-item session-link" href="'+chatURL(s.sessionId)+'" '+(s.sessionId===sessionId&&state!=='empty'?'aria-current="page"':'')+'>'+ico('chat')+'<span>'+esc(s.title)+'</span></a>').join(''));syncLinks()}
renderNav();$$('[data-agent-name]').forEach(e=>e.textContent=agent?.displayName||'Agent unavailable');$$('[data-agent-description]').forEach(e=>e.textContent=agent?.description||'');
if($('.hero .agent-symbol')&&agent)$('.hero .agent-symbol').innerHTML=ico(agent.icon);
function showDialog(d){d._opener=document.activeElement;d.showModal();document.body.style.overflow='hidden'}
function openModal(title,body){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;showDialog($('#modal'));const el=$('#modal-body input,#modal-body textarea');if(el)el.focus()}
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{document.body.style.overflow=$('dialog[open]')?'hidden':'';if(d._opener?.isConnected&&d._opener.getClientRects().length)d._opener.focus();else if(page==='conversation')$('#thread-title')?.focus()});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const list=[...d.querySelectorAll('button,a[href],input,textarea,select,[tabindex="0"]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})});
if($('#open-nav'))$('#open-nav').onclick=()=>showDialog($('#nav-dialog'));
if($('#open-context'))$('#open-context').onclick=()=>showDialog($('#context-dialog'));
const breakpoint=matchMedia('(min-width:1024px)');breakpoint.addEventListener('change',e=>{if(e.matches&&$('#nav-dialog').open){$('#nav-dialog').close();requestAnimationFrame(()=>$('.desktop-nav [aria-current]')?.focus())}else if(!e.matches&&page==='workspace'&&$('#context-wrap').dataset.expanded!=='true'&&$('#context-card').contains(document.activeElement))$('.context-toggle').focus()});
if($('.context-toggle'))$('.context-toggle').onclick=e=>{const expanded=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',expanded);$('#context-wrap').dataset.expanded=expanded};
if($('#review-roster')){$('#review-roster').value=rosterKey;$('#review-roster').onchange=e=>location.href='agents-directory.html?roster='+e.target.value;}
if($('#review-state')){$('#review-state').value=state;$('#review-state').onchange=e=>{state=e.target.value;previewSubmitted='';submittedFromEmpty=false;renderPage();};}
if($('#hide-review'))$('#hide-review').onclick=()=>{document.documentElement.dataset.review='false';syncLinks();renderNav();if(page==='directory')renderDirectory();if(page==='workspace')renderRows();};
function banner(title,body,actions='',kind='error',id=''){return '<section class="state-banner" '+(id?'id="'+id+'"':'')+' role="'+(kind==='error'?'alert':'status')+'"><h2 class="status-'+kind+'">'+ico(kind==='success'?'check':kind==='info'?'info':'warning')+esc(title)+'</h2><p>'+body+'</p>'+actions+'</section>'}
function stateBox(title,body,action=''){return '<section class="state-box"><h2>'+title+'</h2><p>'+body+'</p>'+action+'</section>'}
function action(text,id,primary=false){return '<button class="btn '+(primary?'primary':'outline')+'" id="'+id+'">'+text+'</button>'}
function directoryState(title,body,actionText){return '<section class="empty-directory full-grid">'+ico('grid')+'<h2>'+title+'</h2><p>'+body+'</p>'+(actionText?action(actionText,'directory-retry'): '')+'</section>'}
function renderDirectory(){if(!$('#agent-grid'))return;const input=$('#agent-filter');if(state==='no-results'&&!input.value)input.value='unmatched sample';const query=input.value.trim().toLowerCase();$('#clear-filter').hidden=!query;let entries=roster.filter(a=>(a.displayName+' '+a.description).toLowerCase().includes(query));let html='';if(state==='loading'){html=Array(4).fill('<div class="agent-card" aria-hidden="true"><div class="skeleton short"></div><div class="skeleton"></div><div class="skeleton"></div></div>').join('');$('#agent-count').textContent='Loading agents…'}else if(state==='unavailable'){html=directoryState('Agent configuration unavailable','We couldn’t load the configured agents. No fallback agent has been selected.','Try again');$('#agent-count').textContent='Agent list unavailable.'}else if(state==='empty'){html=directoryState('No agents configured','An administrator needs to configure an agent before you can start a conversation.');$('#agent-count').textContent='0 configured agents'}else if(!entries.length){html=directoryState('No matching agents','Try another name or clear the filter.','Clear filter');$('#agent-count').textContent='0 matching agents'}else{html=entries.map(a=>'<a class="agent-card" href="'+url('workspace.html',{agent:a.agentId})+'"><div class="agent-symbol">'+ico(a.icon)+'</div><h2>'+esc(a.displayName)+'</h2><p>'+esc(a.description)+'</p><span class="card-cta">Open workspace '+ico('chevron')+'</span></a>').join('');$('#agent-count').textContent=entries.length+' '+(entries.length===1?'agent':'agents')+(query?' matching your filter':' available')};$('#agent-grid').innerHTML=html;renderNav();}
if($('#filter-form'))$('#filter-form').onsubmit=e=>e.preventDefault();
if($('#agent-filter'))$('#agent-filter').oninput=()=>{if(state==='no-results')state='populated';renderDirectory()};
function renderRows(){if(!$('#recent-list'))return;let html='';if(state==='loading')html='<div role="status" aria-label="Loading conversations"><span class="sr-only">Loading conversations</span>'+Array(3).fill('<div class="loading-row" aria-hidden="true"><div class="skeleton"></div><div class="skeleton short"></div></div>').join('')+'</div>';else if(state==='unavailable')html=banner('Conversations unavailable','We couldn’t load the list. Your history has not been deleted.',action('Try again','list-retry'),'error');else if(state==='partial')html=banner('Conversation details unavailable','Titles and archive status could not be loaded. Your conversations may still be available.',action('View available conversations','recover-list'),'warning');else if(state==='empty'||!sessions.length)html=stateBox('A fresh start','Your conversations with '+esc(agent.displayName)+' will appear here.','<a class="btn outline" href="'+newURL()+'">Start a conversation</a>');else{if(state==='recovered')html=banner('Recovery view','Titles and archive status are unavailable. Some conversations below may have been archived.','', 'warning');html+=sessions.map((s,i)=>'<div class="recent-row"><a class="recent-open" href="'+chatURL(s.sessionId)+'">'+ico('chat')+'<span><span class="recent-title">'+esc(state==='recovered'?'Untitled conversation '+(i+1):s.title)+'</span><span class="recent-date">'+s.updated+'</span></span></a>'+(state==='recovered'?'':'<button class="icon" data-row-actions="'+s.sessionId+'" aria-label="Actions for '+esc(s.title)+'" aria-haspopup="dialog">'+ico('more')+'</button>')+'</div>').join('')};$('#recent-list').innerHTML=html;}
function renderDocs(){if(!$('#documents'))return;$('#documents').innerHTML=docs.map((d,i)=>'<div class="document"><button class="doc-open" data-doc="'+i+'">'+ico('file')+'<span>'+esc(d)+'</span></button><button class="icon" data-remove-doc="'+i+'" aria-label="Remove sample '+esc(d)+'">'+ico('x')+'</button></div>').join('')||'<p>No sample documents added.</p>';$('#instructions-copy').textContent=instructions;}
function setupContext(){renderDocs();if($('#edit-instructions'))$('#edit-instructions').onclick=()=>{openModal('Edit demo instructions','<p>Changes are not sent to the agent and reset on reload. This does not change backend instructions.</p><label for="demo-instructions">Sample instructions</label><textarea class="field" id="demo-instructions"></textarea><div class="dialog-actions"><button class="btn outline" data-close>Cancel</button><button class="btn primary" id="apply-instructions">Apply to demo</button></div>');$('#demo-instructions').value=instructions;};if($('#add-sample'))$('#add-sample').onclick=()=>openModal('Add a sample document','<p>Choose fictional sample content. No file picker or upload is used.</p>'+['Workspace overview.md','Response preferences.md','Research checklist.md'].map(n=>'<button class="sample-pick" data-pick="'+n+'" '+(docs.includes(n)?'disabled':'')+'>'+ico('file')+'<span>'+n+'</span><span>'+(docs.includes(n)?'Added':'+')+'</span></button>').join(''));}
const codeText='const topics = ["Context", "Questions", "Next steps"];\nconst plan = topics.map((topic, index) => ({\n  step: index + 1,\n  topic,\n}));';
function answerMarkdown(){return 'A useful session starts with **one clear question**. For “'+(activeSession?.title||'A new research session')+'”, separate what you know from what you need to find out.\n\n| Step | Focus | Output |\n| --- | --- | --- |\n| 1 | Context | A short starting summary |\n| 2 | Questions | Three focused questions |\n| 3 | Next steps | One small experiment |\n\nHere is a small example using `map()`:\n\n```javascript\n'+codeText+'\n```\n\nKeep the first pass short. You can refine each step in this conversation.';}
function conversationMarkdown(){return $$('.turn').map(turn=>{const el=turn.querySelector('[data-message-text]');return '## '+(turn.classList.contains('user')?'You':agent.displayName)+'\n\n'+(el.dataset.messageText==='assistant-1'?answerMarkdown():el.innerText)}).join('\n\n');}
function messageActions(id,audio=false){return '<div class="message-actions"><button class="icon" data-copy="'+id+'" aria-label="Copy '+(audio?'assistant response':'your message')+'">'+ico('copy')+'</button>'+(audio?'<button class="icon" data-read="'+id+'" aria-label="Read aloud" '+(params.get('speech')==='unavailable'?'disabled title="Read aloud is unavailable in this browser"':'')+'>'+ico('audio')+'</button>':'')+'</div>'}
function userTurn(text,id='user-1',delivery=''){return '<article class="turn user" aria-label="Your message"><div class="user-message" data-message-text="'+id+'">'+esc(text)+'</div>'+(delivery?'<div class="delivery-note '+(delivery==='Not sent'?'status-error':'status-warning')+'">'+ico('info')+esc(delivery)+'</div>':'')+messageActions(id)+'</article>'}
function baseThread(){const topic=activeSession?.title||'A new research session';return '<div class="thread-meta"><span>Today · 10:42 AM</span><button class="btn ghost" data-copy="conversation" aria-label="Copy conversation as Markdown">'+ico('copy')+'<span>Copy conversation</span></button></div>'+userTurn('Help me outline a focused research session. I’d like a short plan and a small code example.')+'<article class="turn assistant" aria-label="'+esc(agent.displayName)+' response"><div class="assistant-label">'+esc(agent.displayName)+'</div><div class="assistant-copy" data-message-text="assistant-1"><p>A useful session starts with <strong>one clear question</strong>. For “'+esc(topic)+'”, separate what you know from what you need to find out.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Research plan table; scroll horizontally if needed"><table class="message-table"><thead><tr><th>Step</th><th>Focus</th><th>Output</th></tr></thead><tbody><tr><td>1</td><td>Context</td><td>A short starting summary</td></tr><tr><td>2</td><td>Questions</td><td>Three focused questions</td></tr><tr><td>3</td><td>Next steps</td><td>One small experiment</td></tr></tbody></table></div><p>Here is a small example using <code class="inline-code">map()</code>:</p><div class="code-block"><div class="code-head"><span>JavaScript</span><button class="btn ghost" data-copy="code" aria-label="Copy code">'+ico('copy')+'Copy</button></div><pre tabindex="0" role="region" aria-label="JavaScript code; scroll horizontally if needed"><code><span class="syntax-keyword">const</span> topics = [<span class="syntax-string">"Context"</span>, <span class="syntax-string">"Questions"</span>, <span class="syntax-string">"Next steps"</span>];\n<span class="syntax-keyword">const</span> plan = topics.map((topic, index) =&gt; ({\n  step: index + 1,\n  topic,\n}));</code></pre></div><p>Keep the first pass short. You can refine each step in this conversation.</p></div>'+messageActions('assistant-1',true)+'</article>';}
function blockedThread(title,body,actions,kind='error'){return '<div class="empty-thread">'+banner(title,body,actions,kind)+'</div>'}
function setComposer(enabled,help,value){const input=$('#message');input.disabled=!enabled;$('#send').disabled=!enabled||!input.value.trim();$('#chat-help').textContent=help;input.placeholder=enabled?'Ask '+agent.displayName+'…':state==='pending'?'Waiting for reply…':'Sending paused';if(value!==undefined)input.value=value;$('#send').disabled=!enabled||!input.value.trim();}
function renderConversation(){if(!$('#thread-content')||!agent)return;$('#thread-title').textContent=state==='empty'?'New conversation':activeSession?.title||'Conversation unavailable';$('#thread-title').setAttribute('tabindex','-1');const returnLink='<a class="btn outline" href="'+workspaceURL()+'">Back to workspace</a>';const newLink='<a class="btn primary" href="'+newURL()+'">Start a new conversation</a>';let html='',help='Enter to send · Shift + Enter for a new line',enabled=true;
if(state==='empty')html='<div class="empty-thread"><span class="eyebrow">Stark Workspace</span><h2>Chat with '+esc(agent.displayName)+'</h2><p>Send a message to start a separate conversation.</p></div>';
else if(state==='loading'){html='<div class="empty-thread" role="status"><div class="thinking">'+ico('refresh')+'Loading conversation…</div><p>Retrieving this conversation’s history.</p></div>';enabled=false;help='Wait for this conversation’s history to load.'}
else if(state==='unavailable'){html=blockedThread('History unavailable','We couldn’t load this conversation. Its history has not been deleted.','<div class="button-row">'+action('Try loading again','reload-history')+returnLink+'</div>');enabled=false;help='Sending is paused until this conversation’s history is available.'}
else if(state==='missing'){html=blockedThread('Conversation not found','This session is no longer available. It has not been replaced or recreated.','<div class="button-row">'+returnLink+newLink+'</div>');enabled=false;help='Start a new conversation to continue separately.'}
else if(state==='unauthorized'){html=blockedThread('Conversation access unavailable','Your current sign-in does not have access to this conversation. Return to your workspace or use the app’s existing sign-in flow.',returnLink);enabled=false;help='Sending is unavailable for this conversation.'}
else{
html=state==='pending'&&submittedFromEmpty?'':baseThread();
if(state==='pending'){html+=userTurn(previewSubmitted||lastQuestion,'user-2','Awaiting reply')+'<div class="assistant-label">'+esc(agent.displayName)+'</div><div class="thinking" role="status"><span class="thinking-dots" aria-hidden="true"><i></i><i></i><i></i></span>Waiting for a reply…</div><p class="small muted">You can open another conversation while this one waits.</p>';enabled=false;help='A reply is pending in this conversation.'}
if(state==='uncertain'){html+=userTurn(lastQuestion,'user-2','Delivery unconfirmed')+banner('Send outcome unknown','The request timed out. Your message may have reached the agent. Check this conversation’s history before sending anything again.',action('Check history','check-history'),'warning','uncertain-banner');enabled=false;help='Sending is paused while delivery remains unconfirmed.'}
if(state==='failed'){html+=banner('Message not sent','The request did not leave this app. Your draft is preserved below. Review it and send when you’re ready.','', 'error');help='Confirmed not sent. Sending again requires your action.';}
if(state==='metadata')html=banner('Conversation started; title not saved','The conversation exists, but its listing details could not be saved. You can continue here while we check the list.',action('Check conversation list','check-catalogue'),'warning')+html;
}
$('#thread-content').innerHTML=html;setComposer(enabled,help,state==='failed'?lastQuestion:undefined);if(state==='pending'||state==='uncertain'||state==='failed')requestAnimationFrame(()=>$('#thread-scroll').scrollTop=$('#thread-scroll').scrollHeight);else $('#thread-scroll').scrollTop=0;
}
function renderPage(){if(!agent&&page!=='directory'&&page!=='tile'){const main=$('#main-content');main.innerHTML='<section class="invalid-agent">'+banner('Agent unavailable','This agent is not in the selected configuration. Choose an available agent instead.','<a class="btn outline" href="'+url('agents-directory.html')+'">View agents</a>')+'</section>';return;}if(page==='directory')renderDirectory();if(page==='workspace')renderRows();if(page==='conversation')renderConversation();if($('#review-state'))$('#review-state').value=state;}
function changeState(next,notice){state=next;renderPage();if(notice)notify(notice);}
setupContext();renderPage();
if($('#message')){$('#message').oninput=()=>{$('#send').disabled=$('#message').disabled||!$('#message').value.trim();if(page==='conversation'){$('#message').style.height='44px';$('#message').style.height=Math.min($('#message').scrollHeight,144)+'px'}};$('#message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();(page==='workspace'?$('#composer'):$('#chat-composer')).requestSubmit()}};}
if($('#composer'))$('#composer').onsubmit=e=>{e.preventDefault();if($('#message').value.trim()){openModal('Open conversation preview','<p>This standalone design does not send messages. Open the populated conversation fixture to inspect the chat design.</p><div class="dialog-actions"><button class="btn outline" data-close>Keep draft</button><a class="btn primary" href="'+chatURL()+'">Open conversation preview</a></div>')}};
if($('#chat-composer'))$('#chat-composer').onsubmit=e=>{e.preventDefault();if($('#message').disabled||!$('#message').value.trim())return;submittedFromEmpty=state==='empty';previewSubmitted=$('#message').value.trim();$('#message').value='';changeState('pending','Preview only: showing a pending-reply fixture. No message was sent.');};
async function copyText(text){try{await navigator.clipboard.writeText(text);notify('Copied.')}catch{openModal('Copy text','<p>Clipboard access is unavailable. Select and copy the text below.</p><label for="manual-copy">Text to copy</label><textarea id="manual-copy" class="field" readonly></textarea>');$('#manual-copy').value=text;$('#manual-copy').select();}}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close();if(e.target.closest('[data-new]')?.tagName==='BUTTON')location.href=newURL();
if(e.target.id==='clear-filter'||e.target.id==='directory-retry'){state='populated';$('#agent-filter').value='';renderDirectory();$('#agent-filter').focus()}
if(e.target.id==='list-retry'){changeState('populated','Preview list restored; no request was made.')}
if(e.target.id==='recover-list')changeState('recovered');
if(e.target.id==='reload-history')changeState('populated','Preview history restored; no request was made.');
if(e.target.id==='check-history'){const p=$('#uncertain-banner p');p.textContent='Delivery is still unconfirmed. No message has been resent. You can check history again later.';notify('Preview history check: outcome remains unknown. No resend.');}
if(e.target.id==='check-catalogue')notify('Preview only. The existing conversation stays open; no replacement is created.');
const act=e.target.closest('[data-row-actions]');if(act){const s=sessions.find(x=>x.sessionId===act.dataset.rowActions);openModal('Conversation actions','<p>'+esc(s.title)+'</p><label for="rename">Conversation title</label><input class="field" id="rename" maxlength="120" value="'+esc(s.title)+'"><div class="dialog-actions"><button class="btn outline" id="archive-row" data-id="'+s.sessionId+'">Archive</button><button class="btn primary" id="rename-row" data-id="'+s.sessionId+'">Rename</button></div><p class="tile-note" data-preview-only>Fixture changes reset on page navigation or reload.</p>')}
if(e.target.id==='rename-row'){const input=$('#rename');if(!input.value.trim()){input.setCustomValidity('Enter a conversation title.');input.reportValidity();input.oninput=()=>input.setCustomValidity('');return;}sessions.find(x=>x.sessionId===e.target.dataset.id).title=input.value.trim();$('#modal').close();renderRows();renderNav();document.querySelector('[data-row-actions="'+e.target.dataset.id+'"]')?.focus();notify('Preview title changed locally.')}
if(e.target.id==='archive-row'){sessions=sessions.filter(x=>x.sessionId!==e.target.dataset.id);$('#modal').close();renderRows();renderNav();$('#recents-title').setAttribute('tabindex','-1');$('#recents-title').focus();notify('Preview item hidden. No transcript was deleted.')}
const doc=e.target.closest('[data-doc]');if(doc)openModal(docs[Number(doc.dataset.doc)],'<span class="badge">Sample document</span><p style="margin-top:var(--space-4)">This fictional sample describes a workspace for exploring ideas and keeping separate conversations with each agent.</p><p>It is not uploaded, indexed, or sent to the agent.</p><div class="dialog-actions"><button class="btn outline" data-close>Close preview</button></div>');
const remove=e.target.closest('[data-remove-doc]');if(remove){const idx=Number(remove.dataset.removeDoc);docs.splice(idx,1);renderDocs();($$('[data-remove-doc]')[Math.min(idx,docs.length-1)]||$('#add-sample')).focus();notify('Sample removed from this demo only.')}
if(e.target.id==='apply-instructions'){instructions=$('#demo-instructions').value;renderDocs();$('#modal').close();notify('Demo instructions changed locally. Nothing was sent to the agent.')}
const pick=e.target.closest('[data-pick]');if(pick){if(!docs.includes(pick.dataset.pick))docs.push(pick.dataset.pick);renderDocs();$('#modal').close();notify('Sample added locally. No file was uploaded.')}
const copy=e.target.closest('[data-copy]');if(copy){const id=copy.dataset.copy;let text=id==='code'?codeText:id==='conversation'?conversationMarkdown():id==='assistant-1'?answerMarkdown():document.querySelector('[data-message-text="'+id+'"]')?.innerText||'';copyText(text)}
const read=e.target.closest('[data-read]');if(read)notify('Read-aloud control preview. Production retains the existing speech renderer and its browser-support fallback.');
if(e.target.closest('[data-demo]'))notify('Style specimen only. No live action.');
if(e.target.id==='tile-save'){$('#modal').close();notify('Demo changes applied locally.')}
});
if($('#dialog-example'))$('#dialog-example').onclick=()=>openModal('Demo instructions','<p>Changes are not sent to the agent and reset on reload.</p><label for="tile-instructions">Sample instructions</label><textarea id="tile-instructions" class="field">Be clear and practical.</textarea><div class="dialog-actions"><button class="btn outline" data-close>Cancel</button><button class="btn primary" id="tile-save">Apply to demo</button></div>');
