const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=__dirname;
(async()=>{const b=await chromium.launch({executablePath:process.env.DESIGN_CHROMIUM||path.resolve(root,'../render_runtime/chromium'),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});const out=path.join(root,'previews');fs.mkdirSync(out,{recursive:true});let jobs=[];for(const file of ['agents-directory','workspace','conversation','style-tile'])for(const theme of ['dark','light'])for(const width of [375,768,1280])jobs.push({file,theme,width,state:'populated'});
for(const theme of ['dark','light']){for(const state of ['empty','no-results','loading','unavailable'])jobs.push({file:'agents-directory',theme,width:1280,state});for(const state of ['empty','loading','unavailable','partial','recovered'])jobs.push({file:'workspace',theme,width:1280,state});for(const state of ['empty','loading','unavailable','missing','pending','uncertain','failed','metadata','unauthorized'])jobs.push({file:'conversation',theme,width:1280,state});for(const state of ['missing','pending','uncertain','failed'])jobs.push({file:'conversation',theme,width:375,state});jobs.push({file:'agents-directory',theme,width:1280,state:'populated',roster:'alternate'})}
const results=[],extras=[],errors=[],network=[];
for(const j of jobs){const ctx=await b.newContext({viewport:{width:j.width,height:j.width===375?900:1000},deviceScaleFactor:2});const p=await ctx.newPage();p.on('pageerror',e=>errors.push({job:j,error:e.message}));p.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});const qs=new URLSearchParams({theme:j.theme,state:j.state,review:'0'});if(j.roster)qs.set('roster',j.roster);await p.goto('file://'+path.join(root,j.file+'.html')+'?'+qs);await p.evaluate(()=>document.fonts.ready);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const filename=`${j.file}-${j.theme}-${j.width}${j.state!=='populated'?'-'+j.state:''}${j.roster?'-'+j.roster:''}.png`;await p.screenshot({path:path.join(out,filename),fullPage:j.file!=='conversation'});const measures=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth,fontLoaded:document.fonts.check('16px Inter'),documentHeight:document.documentElement.scrollHeight,viewportHeight:innerHeight,composer:document.querySelector('#chat-composer')?(()=>{let r=document.querySelector('#chat-composer').getBoundingClientRect();return{top:r.top,bottom:r.bottom}})():null}));results.push({...j,filename,...measures});
if(j.file==='conversation'&&j.state==='populated'&&j.width===375&&!j.roster){await p.locator('#open-context').click();await p.screenshot({path:path.join(out,`conversation-${j.theme}-375-context.png`)});extras.push(`conversation-${j.theme}-375-context.png`);await p.keyboard.press('Escape');await p.locator('#open-nav').click();await p.screenshot({path:path.join(out,`conversation-${j.theme}-375-navigation.png`)});extras.push(`conversation-${j.theme}-375-navigation.png`);await p.keyboard.press('Escape');await p.locator('.code-block').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,`conversation-${j.theme}-375-code.png`)});extras.push(`conversation-${j.theme}-375-code.png`);await p.locator('#message').focus();await p.keyboard.press('Shift+Tab');await p.screenshot({path:path.join(out,`conversation-${j.theme}-375-focus.png`)});extras.push(`conversation-${j.theme}-375-focus.png`);}
if(j.file==='agents-directory'&&j.state==='populated'&&j.width===1280&&!j.roster){await p.locator('#agent-filter').focus();await p.keyboard.press('Tab');await p.screenshot({path:path.join(out,`agents-directory-${j.theme}-1280-focus.png`),fullPage:true});extras.push(`agents-directory-${j.theme}-1280-focus.png`);}
if(j.file==='workspace'&&j.state==='populated'&&j.width===375){await p.locator('.context-toggle').click();await p.screenshot({path:path.join(out,`workspace-${j.theme}-375-context.png`),fullPage:true});extras.push(`workspace-${j.theme}-375-context.png`);}
await ctx.close()}
const summary={browser:await b.version(),deviceScaleFactor:2,scope:'Offline design artifacts only',results,additionalEvidence:extras,errors,externalRequests:network};fs.writeFileSync(path.join(root,'RENDER_CHECKS.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify({renders:results.length,overflow:results.filter(r=>r.scrollWidth>r.viewport),composerOutsideViewport:results.filter(r=>r.composer&&r.composer.bottom>r.viewportHeight),errors,network}));await b.close();if(errors.length)process.exit(1)})().catch(e=>{console.error(e);process.exit(1)});
